apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: {{ .Release.Name }}-mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: {{ .Values.mongodbUsername }}
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: {{ .Values.mongodbPassword }}
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodbDatabase }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
